### ISSUE TITLE
Option for clearing the backlog

### ISSUE THREAD

**Issue by kraih** [Nordaaker/convos#150]
There will be times when someone posts links to annoying or inappropriate images and those will always get previewed. So just add a "Clear chat" link to the sidebar that kills everything in the backlog to deal with this.

**Comment by tinaira** [comment]
The option of cleaning of the interfaces is necessary because they can be in work working on something ,and doing chit-chat of HOT and comes someone, perhaps the chief and me have a interface clean, NOTE: that deleting it from the backend will also prevent you from searching in the history (when that is implemented in the frontend) regards CONVOS :P

**Comment by ukcb** [comment]
I would be glad if you could disable the logging completely. Some people attach importance to privacy in direct user chats. Where nothing is logged, you do not need to delete anything.

**Comment by jhthorsen** [comment]
Just added "/clear history ..." command.

Better late, than never..? 🙈 

I don't think I will add support for custom backend per user, but you can set `CONVOS_BACKEND="Convos::Core::Backend"` to disable logging for all users.
