### ISSUE TITLE
Add support for image (and generic file) upload

### ISSUE THREAD

**Issue by ludagoo** [Nordaaker/convos#244]
This is a feature request...

I think it would be cool to be able to drag and drop images into the chat. Then behind the curtain convos would upload it to the server and actually send a link to IRC. This would be a great addition to the auto loading of images that convos already does.

---

Comment from @jhthorsen: See also https://github.com/Nordaaker/convos/issues/90

**Comment by jhthorsen** [comment]
I agree. That would be very cool. Not sure when we get time to implement it though...

**Comment by anonsubmitter** [comment]
Adding P2P file transfers using WebRTC and WebTorrent would be cool. No server between the sender and the recipient, so it's faster and more private. You could maybe borrow some code from [FilePizza](https://github.com/kern/filepizza).

**Comment by anonsubmitter** [comment]
Imgur compresses larger photos, so I think that I think either [imgbox](http://imgbox.com/) (10 MB), [vgy.me](https://vgy.me/) (20 MB) or [VoatPic.me](https://voatpic.me/) (100 MB) could be good to add for images that are of high resolution and large filesize. There's also a decentralized, open source image hosting site called [ifps.pics](https://ipfs.pics/).

Here are also a bunch of alternative image hosts:
https://voat.co/v/VoatUserGroup/comments/213792
https://www.reddit.com/r/imguralternatives/top/?sort=top&t=all

And no, I'm not saying that we need to support all of these image hosts. One stable image host that doesn't compress high quality images is enough.

**Comment by jhthorsen** [comment]
Excellent ideas? Also DCC as we discussed yesterday would be nice to have. Either way, I think I will implement my initial idea, since I think it will be the fastest route (for me) to get something working:

* Drag/drop or click upload file. Select one or more files. Upload
* Convos will receive the files and store them under something like ```convos/user@example.com/files```
* Convos generates a unique URL for each file
* Convos will generate a message or fill in the input field with the URL to each of the files.

Each files should have a unique URL. I'm considering one of these:
* http://convos.example.com/api/files/451e0b03-42dd-46d5-897a-97ba2127fcc5.jpeg
* http://convos.example.com/api/files/user@example.com/451e0b03-42dd-46d5-897a-97ba2127fcc5.jpeg

**Comment by systemz64** [comment]
Slack and Hipchat use s3 for their storage - it means you are not limited to images only and its offloaded. I can upload a word file just as easily. You could have this as a configurable option so that I could install my AWS credentials into the system and all storage would be in my aws account. 

This feature would be a big plus point (whether s3 or not)

**Comment by jhthorsen** [comment]
@anonsubmitter: I'm not going to add "crunching" of the images in this iteration. The files gets uploaded and stored exactly how you upload it. Please submit a new issue in 2020, if that's not good enough.

I completely dropped "P2P file transfers", since it's too complicated and I don't really see the benefit. An uploaded file will be stored on the Convos server and a link is shared in the channel or private conversation. The logic is in a plugin though, so you can override the logic however you like.

The file URL looks like this: https://example.com/file/2/1B2M2Y8sgTpgmY7P, where "2" is the UID of the user (keeping the email private) and a hash afterwards, which makes it incredible hard to guess the URL.

I'm reopening this issue though, since there are some things to figure out:

* [ ] - I cannot upload from my iPhone.
* [ ] - Need to figure out a default max image size, and handle error codes if the uploaded file is bigger. The max now is 10MB.
* [ ] - Need to fix the styling of the upload button.

**Comment by jhthorsen** [comment]
It seems like @marcusramberg is able to upload from his iPhone, so I'm closing this for now.
