### ISSUE TITLE
Isolating the backend from the frontend

### ISSUE THREAD

**Issue by Xe** [Nordaaker/convos#248]
Hello,

I've been wanting to deploy this into production via my own dockerfiles for reasons which are immutable to this question. I'm wondering if I can separate the convos backend and frontend into their own containers to separate out the workload across multiple machines and possibly have multiple backends that are load-balanced, etc.

Is this something that can be done easily?

**Comment by jhthorsen** [comment]
Yes. it should be very simple with the current version, since it's divided into three processes:

    backend <=> redis <=> frontend

So each of the components can be started separately, just make sure to set up the right CONVOS_REDIS_URL.

But... We're making a new version, which is a single process so this way of deploying will go away. Can I ask how many people you're serving that makes you require such a setup?

**Comment by Xe** [comment]
I imagine at least fifty, maybe closer to 100.

**Comment by jhthorsen** [comment]
That number of users should not be any problem at all.
