### ISSUE TITLE
Connection timeout when connect to server.

### ISSUE THREAD

**Issue by MagicNAT** [Nordaaker/convos#251]
Got 'Connect timeout' when trying to connect to a IRC server.

    nat@nat ~/convos (git)-[release] % ./vendor/bin/carton exec script/convos daemon --listen http://*:8080
    [Mon Dec 14 20:12:32 2015] [info] Starting convos backend.
    [Mon Dec 14 20:12:32 2015] [info] Listening at "http://*:8080".
    Server available at http://127.0.0.1:8080.
    [Mon Dec 14 20:12:44 2015] [warn] [magicnat:ppy] Could not connect to irc.ppy.sh:6667: Connect timeout
    ^C

However, the server do works, but it does not sent welcome messages. Not sure if that matter.

    nat@nat ~/convos (git)-[release] % telnet irc.ppy.sh 6667
    Trying 192.241.219.151...
    Connected to irc.ppy.sh.
    Escape character is '^]'.
    NICK MagicNAT
    :cho.ppy.sh 372 MagicNAT :Welcome to osu!bancho.
    :cho.ppy.sh 372 MagicNAT :-
    :cho.ppy.sh 372 MagicNAT :- You are required to authenticate before accessing this service.
    :cho.ppy.sh 372 MagicNAT :- Please click the following link to receive your password:
    :cho.ppy.sh 372 MagicNAT :- https://osu.ppy.sh/p/irc
    :cho.ppy.sh 372 MagicNAT :-
    :cho.ppy.sh 464 MagicNAT :Bad authentication token.
    Connection closed by foreign host.

**Comment by Evlos** [comment]
Same issue happened to me when I added some servers with high latency.

I was able to connect these servers through other IRC clients but Convos says timeout.

**Comment by jhthorsen** [comment]
There's a lot of things that doesn't work if the "irc_rpl_welcome" event isn't triggered:

* Mojo::IRC won't do keep alive ping to prevent timeout
* Convos won't send automatic JOIN commands to the IRC server
* "attempts" won't be reset in Convos::Core::Connection, meaning it will take "forever" to reconnect

I think the default timeout is 15 seconds (need to check to be sure), when it comes to connect timeout... Does it take longer than that to connect?
What other event do you suggest we trigger on, instead of "welcome" ?
Are you in charge of the IRC server?
Why doesn't it send a welcome message?

**Comment by Evlos** [comment]
@jhthorsen 

The default timeout should be 10 seconds, if I didn't get it wrong.

```
weaken $self;
  my $reactor = $self->reactor;
  $self->{timer} = $reactor->timer($args->{timeout} || 10,
```

And yes, in my situation, it took longer than 10 seconds to connect.

**Comment by jhthorsen** [comment]
Ok... I'm sorry to say that I won't be able to fix that in the current version of Convos. The reason for this is that Convos require some older version of the different dependencies which makes me unable to fix the issue.

But if you installed Convos using carton, you could hack it yourself for now.

```
git clone https://github.com/Nordaaker/convos
cd convos
./vendor/bin/carton install
vim local/lib/perl5/Mojo/IRC.pm
# Add "timeout => 60," to line 249
# Restart Convos
```

I'm leaving this issue open, so I can add this to Mojo::IRC and then to the next version of Convos.

**Comment by Evlos** [comment]
@jhthorsen 

```
Connected to IRC server
Could not send message to http://localhost:60025/ Not connected
Could not connect to 203.86.204.248:6667: Connect timeout
Could not connect to 203.86.204.248:6667: Connect timeout
You are not yet connected to 203-86-204. If this status does not change soon, you should contact your system administrator and let him/her know about the issue. Maybe the backend is not running?
```

After I hacked it, I found `Connected to IRC server` in the log, but it got timeout after around 1 minutes. It looks kinda weird, any idea what happened?

The server address is `203.86.204.248:6667` owned by someone else.

**Comment by jhthorsen** [comment]
The last "You are not yet connected" message sounds like your browser does not support websockets or there's some proxy blocking the traffic.

When it comes to superslow/non-responsive IRC servers... I really think "someone" should fix internet/the IRC server instead of fixing Convos/Mojo::IRC. Not being able to connect in 10 seconds is really odd.

**Comment by jhthorsen** [comment]
Pretty sure this works in https://github.com/Nordaaker/convos/tree/one-point-oh

**Comment by jhthorsen** [comment]
Closing this issue, because it has gone stale.

Please check out https://convos.by/doc/install.html if you want to test the new code base.
