### ISSUE TITLE
Messages are grouped incorrectly on scrollback

### ISSUE THREAD

**Issue by marcusramberg** [Nordaaker/convos#301]
When you scroll back, messages are sometimes grouped together incorrectly, giving the impression that the wrong person wrote something.

**Comment by jhthorsen** [comment]
Pretty sure the issue is in `Convos.Dialog.prototype._processMessages`: The problem is that there are some places where `messages.push()` and `messages.unshift()` are used directly. This will mess up `msg.prev`, which is used to track who sent which message. The solution is to always use `addMessage()` and add another method for removing a message and at the same time keep track of the correct `msg.prev`.

That is my best theory so far.

**Comment by jhthorsen** [comment]
This should be fixed in the commit above, but I fail to make a test case for it. Either way, the commit contains code that *should* avoid the problem all together, since it does not use "msg.prev".
