### ISSUE TITLE
Does not support "away" ?

### ISSUE THREAD

**Issue by ekianjo** [Nordaaker/convos#305]
It says that this is an unknown irc command when you type /away message - is that not implemented yet?

**Comment by jhthorsen** [comment]
No, it is not implemented. Simply because I don't use it myself. This needs a change in both Mojo-IRC and Convos I think...

Not sure when I'm going to implement it. I will however take a PR. The files that need changing are:

* https://github.com/Nordaaker/convos/blob/master/lib/Convos/Core/Connection/Irc.pm#L196
* Maybe we need a new away() method in Mojo-IRC, https://github.com/jhthorsen/mojo-irc/blob/master/lib/Mojo/IRC/UA.pm
* Tests.

It will be implemented faster, if there are more interest.

**Comment by ekianjo** [comment]
well I would use it myself at least. Please let us know when you have something that may be working :)

**Comment by marcusramberg** [comment]
This isn't something the core group sees a need for, but we'd welcome a pull request that implements the feature.

**Comment by jhthorsen** [comment]
There have been new development in this issue now. See https://github.com/Nordaaker/convos/issues/317 for details.

**Comment by jhthorsen** [comment]
This should be fixed in "master" now. Hoping to get a new release out in the end of the week.
