### ISSUE TITLE
Handle multiline messages better

### ISSUE THREAD

**Issue by Gouthamve** [Nordaaker/convos#328]
Currently multi-line messages pasted from an external source are being concatenated and sent as a single message. We need to handle them better.

It was suggested that:
1. We make a paste for long messages.
2. But if the messages are only 2-3 lines long, we send each line as a different message.

After this also add the ability to compose multiline messages in the input-box itself. Now, hitting `control+Return` or `Shift+Return` posts the message.

**Comment by jhthorsen** [comment]
"shift+return" toggles between the "search box" and "message box". I'm not sure if there is a usecase for being able to compose multiline messages directly. I can only see the case where you copy/paste from some other source.

**Comment by jhthorsen** [comment]
I believe the commit above handles multiline messages a lot better:

* Convos now splits on newline and sends the parts as separate messages
* Currently it supports max three lines, but it can be configured with an environment variable (EXPERIMENTAL)

TODO: Would be cool to be able to create paste, but I'm not sure where to implement it. I would like to do it in the "controller" instead of in the "connection" class, but right now it's not very easy to do, since it's the "connection" class that understand if a message is a plain message or a command.

It could be possible to have the code below and let a plugin handle "multiline_message" events.

```
if (MAX_BULK_MESSAGE_SIZE < @messages) {
  return $self->emit(multiline_message => $message, $cb);
}
```

Just need another method than "emit()", since we need to ensure that `$cb` gets called to provide feedback to the user.

**Comment by jhthorsen** [comment]
Opened a PR now: https://github.com/Nordaaker/convos/pull/329
