### ISSUE TITLE
Snap setup (can't access) doesn't appear in port 3000 

### ISSUE THREAD

**Issue by Apperator** [Nordaaker/convos#366]
Fresh Ubuntu 16.04

Snap installed
`snap install convos`

Can't access convos in browser. Port 3000 and localhost don't return anything.

**Comment by marcusramberg** [comment]
Hi, I'm [GitMate.io](https://gitmate.io)!

It seems you've just enabled the issue triaging. I'm just scraping all issues from your repository and will give you some more information about this in a few minutes or so.

Because of the rate limit we can't scrape all information (including all comments and authors) right now - our system is already set up to scrape this in the next days over which the predictions will become more precise every day.

If you want me to use a different account for triaging your issues, simply create one and log in with it.

**Sit tight!**

**Comment by marcusramberg** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @jhthorsen.

**Comment by jhthorsen** [comment]
I'm not sure what's going on... I tried to build a snap for the 1.00 release, but I'm unable to:

```
$ bash ./snap/build.sh 
+ snap list convos
error: no matching snaps installed
+ sudo snapcraft cleanbuild
Creating snapcraft-oddly-moving-gull
Starting snapcraft-oddly-moving-gull
error: flag provided but not defined: --format
Failed to get container image info: `lxc image list --format=json ubuntu:xenial/amd64` returned with exit code 2, output: b''
It will not be recorded in manifest.
Waiting for a network connection...
Failed to open 'http://start.ubuntu.com/connectivity-check.html': timed out
Failed to open 'http://start.ubuntu.com/connectivity-check.html': timed out
Failed to open 'http://start.ubuntu.com/connectivity-check.html': timed out
Failed to open 'http://start.ubuntu.com/connectivity-check.html': timed out
Failed to open 'http://start.ubuntu.com/connectivity-check.html': timed out
Stopping local:snapcraft-oddly-moving-gull
Failed to get a network connection in the container: could not successfully ping 'start.ubuntu.com'.
If using a proxy, check its configuration. Refer to the documentation at https://linuxcontainers.org/lxd/getting-started-cli.
```

Do you know what's going on? The server has access to internet, and I can `curl http://start.ubuntu.com/connectivity-check.html` from the command line.

**Comment by jhthorsen** [comment]
I'm going to close this in favour of #421.
