### ISSUE TITLE
Retry the connection after N*2 seconds if it fails

### ISSUE THREAD

**Issue by serhack** [Nordaaker/convos#410]
I just noticed a frustrating issue. Sometimes when you try to reach too much a server, it could put you in a queue list and you have to wait some seconds (usually one or two) to re-try. With the current version (1.0.1), my Convos installation tries to reach the server every ~500ms. 
Can't we add a progressive timer for new connections if those fail? 

Pseudocode

```
# in seconds
n = 1
if connection fails
    n = n*2;
    wait(n);

retry_connection
```

**Comment by jhthorsen** [comment]
I find that very difficult to believe that you get reconnected after 500ms. There are some tests that says otherwise, and we used to have a lot of issues being kicked off before the tests and logic was in place.

The only exception is if you connect to "localhost". Doing so is almost instantly. The reasoning behind this is that whoever set up "localhost", is probably also in charge of Convos, and can therefor change the IRC server settings to allow instant connections for all users.

Either way: In b2dddd9, I've added a safe guard that looks for the "Trying to reconnect too fast." message that is sent by the IRC server (at least some) and will sort of use the same logic as in your pseudocode.

FYI: The reconnect timer can be configured though. `CONVOS_CONNECT_DELAY` default to 4 seconds, but can be set to 0.5. Doing so, will result in what you describe in the issue description.
