### ISSUE TITLE
Does not send "/foobar" to the IRCd, dumps into query or channel window instead.

### ISSUE THREAD

**Issue by RealKindOne** [Nordaaker/convos#428]
**Describe the bug**
Clients are supposed to send anything starting with a "/" to the IRCd.. Right now convos just prints the command into whatever channel or query window. This is bad as some people use "/nickserv" instead of "/ns". 

**To Reproduce**
1. Join Channel or Query someone.
2. Type "/nickserv identify password"
3. The entire channel or person you in the query window now has your password.

**Expected behavior**
Send command to IRCd, not into channel or query windows.

**Comment by jhthorsen** [comment]
The idea was that it's confusing for many basic users that "/some message" needs to be prefixed with `/say` to be sent as a normal message.

Your argument about `/nickserv identify password` is a very good reason for removing support for "/some message" though, so that's what I did in 4cff01a. I also add support for "/raw " in case someone wants to send an command that is not supported by Convos.
