### ISSUE TITLE
Audio conferencing with Mumble?

### ISSUE THREAD

**Issue by poVoq** [Nordaaker/convos#451]
**Is your feature request related to a problem? Please describe.**
WebRTC is not very scalable to multiple participants unless a bridging solution like Jitsi Meet is used. However this seems to have been discarded: 
https://github.com/Nordaaker/convos/issues/204

**Describe the solution you'd like**
While 1:1 Video chats with WebRTC would be still nice to have, Discord like audio channels with many participants would be also cool.
The best idea is probably to build on the existing Mumble/Murmur system that is very reliable and offers very high quality and low latency audio conferencing at minimal server load.
There is also an working but somewhat experimental webclient for it:
https://github.com/Johni0702/mumble-web

**Describe alternatives you've considered**
Utilizing Jitsi Meet is a option.

Thanks for considering :)

**Comment by poVoq** [comment]
There are also some existing IRC to Mumble bridges:

https://github.com/aheadley/doty

https://github.com/SFTtech/sftmumblebot

https://github.com/narenniranjan/broadcast

**Comment by jhthorsen** [comment]
Convos is (mostly) about being self-contained, so you don't have to install a bunch of additional software to get it up and running. I do want to keep it this way, so that is the reasoning behind #204.

What I do like about your suggestion though is that it at least cares about privacy, meaning you can install and run your own mumble instance, instead of using a 3rd party system.

What I don't like is that it video is not supported. https://wiki.mumble.info/wiki/Planned_Features#Video

I'm keeping this issue open, but I don't see myself putting a lot of energy into it.

**Comment by poVoq** [comment]
I wouldn't hold my breath for video support in Mumble, but audio is rock solid.

I understand your argument, but since Convos also requires a 3rd party IRC server, running a easy to host Murmur server next to it seems quite strait forward.

**Comment by jhthorsen** [comment]
I don't think we will implement this, so I'm putting this issue in the [fridge](https://github.com/Nordaaker/convos/milestone/20).

**Comment by jhthorsen** [comment]
I'm moving this issue to the 4.xx milestone, since I've implemented WebRTC support instead.

**Comment by poVoq** [comment]
Someone is working on WebRTC support for Mumble though ;)

https://github.com/mumble-voip/mumble/issues/3561

**Comment by poVoq** [comment]
@jhthorsen since you moved to Jitsi via iframe now, would you reconsider this?

https://github.com/Johni0702/mumble-web

Is now stable and WebRTC based and could be embedded very similar to Jitsi. In fact for Matrix widgets it simply replaces the Jitsi widget.

Although Discord like audio-channels with a mumble backend would be even cooler.
