### ISSUE TITLE
Pages 'Not Found'

### ISSUE THREAD

**Issue by instalab** [Nordaaker/convos#487]
**Describe the bug**
Just as in the title, I've tried 2 pages:
 - / (aka index page)
 - /login
Both pages show the following screen:
![Screenshot_2020-05-29_21-34-51](https://user-images.githubusercontent.com/23265116/83303020-416d5d80-a1f4-11ea-8566-fd9d39f85324.png)
 
**To Reproduce**
Here are a few things about the server I am running convos on:
 - I am using docker container 'nordaaker/convos:stable'
 - I have the environment variable set: 'CONVOS_REVERSE_PROXY: 1'
 - Container is called 'convos'
 - Volume: 'data:/data'
 - Convos is running behind Traefik reverse proxy, Traefik listens on the default https port and gets the certificate from Lets Encrypt, then it routes the request to the convos container on the following URL: http://convos:3000/
 - I use the same traefik configuration for other services like gitlab and wikijs, until now everything worked.
 - Convos is only accessible from behind VPN

**Expected behavior**
I should see the login page.

**Screenshots**

**Environment:**
 - OS: Arch Linux (server and host work on the same OS but different machines)
 - Browser Chromium Version 83.0.4103.61 (Official Build) Arch Linux (64-bit)

**Additional context**
Request snapshot:
[request.har.zip](https://github.com/Nordaaker/convos/files/4704245/request.har.zip)
Try inspecting it with a tool like this: http://www.softwareishard.com/har/viewer/

**Comment by jhthorsen** [comment]
It looks like you forgot to set the `X-Request-Base` header. If you want, you can set `CONVOS_REVERSE_PROXY` instead of `CONVOS_REVERSE_PROXY` and `X-Request-Base`:

```
CONVOS_REQUEST_BASE: https://example.com/
```

See the resources below for more information:
* https://convos.chat/doc/faq.html#can-convos-run-behind-behind-my-favorite-web-server
* https://convos.chat/doc/config.html

I just pushed a new version of the documentation to make this a bit clearer. Please let me know if it could be improved further. a7d08f29
