### ISSUE TITLE
Button for Nick change, change password, etc

### ISSUE THREAD

**Issue by TimeRider07** [Nordaaker/convos#489]
It would be really cool if we had a button to change nickname and similarly a box to change password for convos users.

**Comment by jhthorsen** [comment]
What do you mean with "box to change password for Convos users"? Which password do you want to change? (The login password can already be changed from the "Account" page)

**Comment by jhthorsen** [comment]
Also, the nickname can be set from the connection settings.

**Comment by TimeRider07** [comment]
Hello jhthorsen, I meant password for Nickserv (Anope IRC Services). If registration and change of password (Nickserv) could be handled by the convos client, it would be really nice. It could be in "Account" section.

I know Nickname could be changed from setting, but I think a button / box to change nickname would be more easy and convenient for convos users to find and use.

**Comment by jhthorsen** [comment]
I'm not sure where that nick changing button would be placed though. On desktop (wide screens) it could be placed on the left side of the input (I think), but that won't work on smaller screens.

**Comment by jhthorsen** [comment]
About "password for Nickserv" -- What is the difference from #488 ?

**Comment by TimeRider07** [comment]
> I'm not sure where that nick changing button would be placed though. On desktop (wide screens) it could be placed on the left side of the input (I think), but that won't work on smaller screens.

It could be besides the "setting" at the top or "send" at the bottom. Also, it is possible to keep below "Add connection" menu.



> About "password for Nickserv" -- What is the difference from #488 ?

That thread is specifically for registration of nickname in Nickserv and a pop up of password box for identified users which can be triggered on the notice message"-NickServ- This nickname is registered and protected."

**Comment by jhthorsen** [comment]
> It could be besides the "setting" at the top or "send" at the bottom. Also, it is possible to keep below "Add connection" menu.

That won't work if you have multiple connections. Also, I cannot add a dedicated menu option for this, since it might open up for a lot more menu options / shortcuts that people might want. If it's hard to find the settings for a connection, then maybe it could be an idea to change "Add connection" to just "Connections" and let the user mange and add connections from there.

> password for Nickserv
Please extend the description for #488, since it's much more related to that issue. This issue is no good, since it involves two very different topics.

...for that reason I'm going to close this issue. Please open a new issue if you think the "Connections" menu option is a good idea, or if you have any other ideas on how to improve the user experience.
