### ISSUE TITLE
Rename IRC Connections

### ISSUE THREAD

**Issue by wylel** [Nordaaker/convos#507]
**Describe the solution you'd like**
Add the option to rename IRC connections. Some return just "irc" as the name. The ability to rename that would be nice for organization.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by jhthorsen** [comment]
What do you mean it just returns "irc"? Does that mean "irc-irc", "irc-" or something else?

**Comment by wylel** [comment]
Meaning irc-irc. So on the left column I have one server (freenode) labeled "freenode", and another server labeled "irc"

**Comment by jhthorsen** [comment]
That's strange. https://github.com/Nordaaker/convos/blob/9c357e16bcfa1c13d8a6d8654f55a63ec9da5f1f/lib/Convos/Util.pm#L90 has some rules which is supposed to generate a prettier connection name. Can you provide me with the complete hostname for the IRC server?

It's not impossible to add functionality for editing the connection names, but I'm not too keen on implementing it, since it will make it (a bit) harder to understand which network a user is connected to.

**Comment by wylel** [comment]
As an example, I cannot input ircs://irc.oftc.net:6697 (it forces me to just put irc.oftc.net:6697 although the example shown is irc://chat.freenode.net:6697, still works regardless).

When I add the above irc.oftc.net:6697 it renames it as ircs. The other server I connected to, irc.darkscience.net:6697 renamed itself to irc (or ircs-ircs irc-irc respectively).

**Comment by jhthorsen** [comment]
Thanks for the details!

I've updated the help section for ConnectionForm, though you won't see that fix until I make a new release, or you manually build the javascript from master. aa591a6

I've also improved/fixed some issues with generating pretty connection names. cea07b9

Unfortunately I cannot prioritize fixing this issue now, but I've updated the FAQ with information on how you can fix this manually: https://convos.chat/doc/faq#can-i-rename-my-connection-names

**Comment by jhthorsen** [comment]
Going to put this in the fridge, since it's documented how to do it manually and the issue where the calculated connection name is fixed.
