### ISSUE TITLE
Delay Commands on Connect

### ISSUE THREAD

**Issue by wylel** [Nordaaker/convos#517]
**Is your feature request related to a problem? Please describe.**
I have a server I want to pass 2 commands to, but the second cannot be done until the first one is done.

**Describe the solution you'd like**
The ability to delay commands, or have a nickserv command (since some servers require username and some do not) and a separate box for commands that come after that one is issued.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by jhthorsen** [comment]
How will delay work? As in, how do you know how long to wait?

“After that one is issued” is a bit difficult to implement, since different commands will trigger different events, and some does not trigger any events.

Do you have a real list of commands that you want to run? An example might make the final solution much better. For now, just add “/sleep 4.2” (where 4.2 is in seconds) where you need to wait.

**Comment by wylel** [comment]
From what I understand, those additional commands get passed after the server says its connected. If I am wrong let me know.
```
/msg nickserv idenify password
/sleep 5
/msg otheruser enter #channel password
```
