### ISSUE TITLE
Add LDAP support

### ISSUE THREAD

**Issue by nedos** [Nordaaker/convos#65]
It would be nice to have some other authentication mechanisms and LDAP in particular. I'm sure I'm not the only one keen on running something like this on a subnet far far away with sufficient infrastructure for user authentication.

**Comment by jhthorsen** [comment]
Closing this, since we don't have the power to implement it. Going for #89 instead.

**Comment by jhthorsen** [comment]
@nedos: Not sure if it's too late or not, but I'm working on LDAP support now in #418.

**Comment by poVoq** [comment]
This seems to be largely undocumented. Would it be possible to add an example configuration to the Convos documentation that works with a [simple LDAP server](https://github.com/nitnelave/lldap/)?

Any chance that there could be an option to pass through the login details to a preconfigured IRCd via SASL auth, so that users could directly authenticate on an Ergo.chat server that uses the [LDAP auth](https://github.com/ergochat/ergo-ldap) extension?

Thanks!

**Comment by jhthorsen** [comment]
Did you look at https://convos.chat/doc/Convos/Plugin/Auth/LDAP ?

I don't know how sending LDAP to the IRCd works and I doubt I will find time to look into it. I welcome a PR and/or an issue with more details though.
